// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config'
try {
    process.loadEnvFile()
} catch {}

export default defineConfig({
    schema: 'src/prisma/schema.prisma',
    migrations: {
        path: 'src/prisma/migrations',
    },
    datasource: {
        url: process.env['DATABASE_URL'],
    },
})
